port: PORT
logLevel: LOG_LEVEL
baseUrl: BASE_URL

directories:
  originals: ORIG_DIRECTORY
  edited: EDITED_DIRECTORY

overlay:
  image: OVERLAY_IMAGE
  size: OVERLAY_SIZE
  position: OVERLAY_POSITION

imageSize: IMAGE_SIZE
