port: 3000
logLevel: debug
baseUrl: http://localhost:3000

directories:
  originals: images/original
  edited: images/edited

overlay:
  image: images/snowball-logo.svg
  size: 200
  # can be any one of the supported sharp.gravity constants
  position: center

imageSize: 400
